### ISSUE TITLE
Ruber Banding

### ISSUE THREAD

**Issue by EmeraldDragonGamer** [LeronDoesGM/ParadiseCraft-Bug-Reports#5]
#### Description
On the windows 10 edition on ParadiseCraft when walking it sometimes brings you down or back. Doesn't happen as much on mcpe. This occurs in normal lobby and a lot on the parkour game lobby.

**Comment by Shavinda101** [comment]
Although this bug is not rubber banding. Once again rubber banding is fixed. This issue has to occur because of the flying anti cheat. I will see what I can do to avoid this from happening. But, it seems right now it will just be this way Incase of fly hackers. Parkour won’t be on the server as a gamemode anymore due to this.
